# Generated by Django 4.2.1 on 2023-12-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Delivery_Information',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Care',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
